### ISSUE TITLE
期望有新功能设置窗口大小

### ISSUE THREAD

**Issue by swRains** [Zonciu/War3FixFont#5]
期望能设置窗口大小和比例，每次窗口启动都得手动拖下窗口大小，如果能自动设置下会很方便。
全屏的话拉伸啥的会很难受，我还是喜欢4:3
期望作者大大能考虑下
非常感谢！！

**Comment by Zonciu** [comment]
可以

**Comment by Zonciu** [comment]
已更新v1.7

**Comment by swRains** [comment]
> 已更新v1.7

我超，爽歪歪，感谢大佬！
我自己写的几个脚本可以改变其他窗口大小除了war3，也不知道为啥
